### ISSUE TITLE
Student Project

### ISSUE THREAD

**Issue by datafunk** [learn-javascript-courses/checkin#2]
Hi [Eric](@ericelliott),

Thanks for the awesome day of insights and learnings.
Here's [Imad](@isader)'s and [my](@datafunk) app as far as we managed to take it within the time given...

https://github.com/datafunk/checkin_app

Would love to hear back with any feedback and suggestions.

Cheers

**Comment by ericelliott** [comment]
Looking good so far. Love the mock data approach.

Some comments:
- Try using ES6 modules instead of Bower
- Try React. It's fun!
- I would create distinct views rather than trying to cram everything into one screen. Try React Router or Page.js for routing to different views.

**Comment by datafunk** [comment]
Yes I guess we didn't really move out of our comfort zone... :( Need to test the waters a bit before diving in, new syntax and all...
[Imad](@isader) suggested the multiview, so my bad for pushing for the single view.
