### ISSUE TITLE
Cody Loyd + Thoragio project

### ISSUE THREAD

**Issue by codyloyd** [learn-javascript-courses/checkin#4]
https://github.com/codyloyd/checkin

https://check-it-9989.herokuapp.com/

🌮 🍕 🍺

**Comment by codyloyd** [comment]
@ericelliott.. just wondering if you've seen this yet

**Comment by thoragio** [comment]
Currently seeing some issues with Heroku, so it has been deployed to [now.sh](https://checkit-cgknsqwmvc.now.sh) as well.

**Comment by codyloyd** [comment]
🔥

**Comment by ericelliott** [comment]
Feedback:

* Where are the unit tests? I see a lot of code that doesn't seem to have any tests. See ["The Outrageous Cost of Skipping TDD and Code Review"](https://medium.com/javascript-scene/the-outrageous-cost-of-skipping-tdd-code-reviews-57887064c412)
* Group by feature, not by file type. Colocate related code. See ["Elements of JavaScript Style"](https://medium.com/javascript-scene/elements-of-javascript-style-caa8821cb99f)
